version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Manila
  automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  open-pull-requests-limit: 10
  target-branch: preview
