language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn global add codecov
  - yarn

script:
  - yarn test
  - yarn build

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHP_PUBLISH
  keep_history: true
  on:
    branch: master
